image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - server/node_modules/

install_dependencies:
  stage: build
  before_script:
    - cd server
  script:
    - npm install
    - ls 

foreverdeploy:
  stage: deploy
  before_script:
    - ls
    - ls server
    - forever stop server/server.js || true
  script: forever start server/server.js -k ~/server.key -c ~/server.crt
