image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - server/node_modules/

install_dependencies:
  stage: build
  before_script:
    - cd server
  script:
    - npm install
    
nodetest:
  stage: test
  before_script:
    - cd server
  script:
    - npm test

foreverdeploy:
  stage: deploy
  before_script:
    - forever stop server/server.js || true
  script: forever start server/server.js -k ~/server.key -c ~/server.crt -b ~/project-talk_me.ca-bundle
